// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqvorvszkhoieruhfnbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdxdm9ydnN6a2hvaWVydWhmbmJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNDUzNDMsImV4cCI6MjA1ODgyMTM0M30.Um3a34MjuNIDcPm4XjUCb7b_QSW-5ziXGSEFI-RgcGU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);